# Generated by Django 4.2.30 on 2026-06-09 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload a clear image of the venue/hall layout.', upload_to='floor_plans/')),
                ('natural_width', models.PositiveIntegerField(default=0)),
                ('natural_height', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plan', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_number', models.CharField(help_text='e.g. A1, B3, Table-12', max_length=20)),
                ('label', models.CharField(blank=True, help_text='Optional display name.', max_length=100)),
                ('category', models.CharField(choices=[('FOOD', 'Food & Beverage'), ('MERCH', 'Merchandise'), ('ARTS', 'Arts & Crafts'), ('SERV', 'Services'), ('COLL', 'Collectibles'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('x_percent', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('y_percent', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('width_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PENDING', 'Pending'), ('RESERVED', 'Reserved'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal organizer notes. Not shown to merchants.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booths', to='booths.floorplan')),
            ],
            options={
                'ordering': ['booth_number'],
                'unique_together': {('floor_plan', 'booth_number')},
            },
        ),
    ]
