# Generated by Django 4.2.30 on 2026-06-14 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='proof_image',
            field=models.ImageField(upload_to='payment_proofs/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option', models.CharField(choices=[('full_only', 'Full Payment Only'), ('half_half', '50/50 — Half Now, Half Later'), ('both', 'Both Options Available')], default='full_only', max_length=20)),
                ('second_payment_deadline_days', models.PositiveIntegerField(blank=True, help_text='Days before the event start date that second payment is due.', null=True)),
                ('reservation_expiry_hours', models.PositiveIntegerField(default=24, help_text='Hours the merchant has to submit payment proof before slot is released.')),
                ('terms_and_conditions', models.TextField(default="Welcome to CONTRACK. By reserving a booth or stall through this platform, you agree to the following terms:\n\n1. Reservation is only confirmed upon review and approval of your payment proof by the organizer.\n\n2. Full payment must be completed before the event date. For 50/50 arrangements, the second payment must be submitted by the stated deadline.\n\n3. Failure to submit payment proof within 24 hours of reservation will result in automatic cancellation of your slot.\n\n4. Refunds are subject to the organizer's discretion and cancellation policy.\n\n5. The organizer reserves the right to deny any reservation without obligation to disclose a reason.\n\n6. Slot assignments are final once confirmed. Requests for slot changes are subject to availability.\n\nFor concerns, contact the organizer directly via the details provided in your confirmation.")),
                ('organizer_name', models.CharField(blank=True, max_length=200)),
                ('organizer_phone', models.CharField(blank=True, max_length=30)),
                ('organizer_email', models.EmailField(blank=True, max_length=254)),
                ('organizer_facebook', models.URLField(blank=True)),
                ('gc_messenger_link', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.OneToOneField(limit_choices_to={'role': 'ORGANIZER'}, on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='payment_qr/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(limit_choices_to={'role': 'ORGANIZER'}, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
